/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tap_u1p6_b;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Link
 */
public class CapturadorMateriasFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form CapturadorMateriasFrame
     */
    Color colorPrimaryDark = new Color(69, 67, 164);
    Color colorSecundaryDark = new Color(49, 38, 131);
    Color colorPrimaryLigth = new Color(87,134,236);
    Color colorSecundaryLigth = new Color(0,102,255);
    
    
    public CapturadorMateriasFrame() {
        
        initComponents();
        btnDarkLightMode.setIcon(new ImageIcon("src\\main\\java\\Images\\light-mode.png"));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        btnDarkLightMode = new javax.swing.JToggleButton();
        panelMenu = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnCapturador = new javax.swing.JButton();
        btnTemario = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDarkLightMode.setBackground(new java.awt.Color(87, 134, 236));
        btnDarkLightMode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDarkLightMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarkLightModeActionPerformed(evt);
            }
        });
        bgPanel.add(btnDarkLightMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 40, 40));

        panelMenu.setBackground(new java.awt.Color(87, 134, 236));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitulo.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Capturador");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelMenu.add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 40));

        btnExit.setBackground(new java.awt.Color(87, 134, 236));
        btnExit.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Salir");
        btnExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panelMenu.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 210, 40));

        btnCapturador.setBackground(new java.awt.Color(87, 134, 236));
        btnCapturador.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnCapturador.setForeground(new java.awt.Color(255, 255, 255));
        btnCapturador.setText("Capturador");
        btnCapturador.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCapturador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturadorActionPerformed(evt);
            }
        });
        panelMenu.add(btnCapturador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 40));

        btnTemario.setBackground(new java.awt.Color(87, 134, 236));
        btnTemario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnTemario.setForeground(new java.awt.Color(255, 255, 255));
        btnTemario.setText("Ver temario");
        btnTemario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTemario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemarioActionPerformed(evt);
            }
        });
        panelMenu.add(btnTemario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 40));

        btnAyuda.setBackground(new java.awt.Color(87, 134, 236));
        btnAyuda.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAyuda.setForeground(new java.awt.Color(255, 255, 255));
        btnAyuda.setText("Ayuda");
        btnAyuda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        panelMenu.add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 243, 210, 40));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        panelMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        panelMenu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 193, 190, 10));

        bgPanel.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 390));

        menuBar.setBackground(new java.awt.Color(87, 134, 236));
        menuBar.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Inicio");

        jMenuItem1.setText("Capturador");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Ver temarios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        menuBar.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem4.setText("Acerca de...");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new CapturadorAsignaturaFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JOptionPane.showMessageDialog(null,"By: Salvador Alejos Soria");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnDarkLightModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarkLightModeActionPerformed
        // TODO add your handling code here:
        if(btnDarkLightMode.isSelected()){
            menuBar.setBackground(colorPrimaryDark);
            menuBar.setForeground(Color.WHITE);
            btnDarkLightMode.setIcon(new ImageIcon("src\\main\\java\\Images\\dark-mode.png"));
            btnDarkLightMode.setBackground(new Color(69, 67, 164));
            panelMenu.setBackground(colorPrimaryDark);
            panelTitulo.setBackground(colorSecundaryDark);
            btnCapturador.setBackground(colorPrimaryDark);
            btnAyuda.setBackground(colorPrimaryDark);
            btnTemario.setBackground(colorPrimaryDark);
            btnExit.setBackground(colorPrimaryDark);
            FlatDarkLaf.setup();
        }else{
            menuBar.setBackground(colorPrimaryLigth);
            menuBar.setForeground(Color.BLACK);
            btnDarkLightMode.setIcon(new ImageIcon("src\\main\\java\\Images\\light-mode.png"));
            btnDarkLightMode.setBackground(colorPrimaryLigth);
            panelMenu.setBackground(colorPrimaryLigth);
            panelTitulo.setBackground(colorSecundaryLigth);
            btnCapturador.setBackground(colorPrimaryLigth);
            btnAyuda.setBackground(colorPrimaryLigth);
            btnTemario.setBackground(colorPrimaryLigth);
            btnExit.setBackground(colorPrimaryLigth);
            FlatLightLaf.setup();
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_btnDarkLightModeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if(btnDarkLightMode.isSelected()){
            menuBar.setBackground(new Color(69, 67, 164));
            menuBar.setForeground(Color.WHITE);
            btnDarkLightMode.setIcon(new ImageIcon("src\\main\\java\\Images\\dark-mode.png"));
            btnDarkLightMode.setBackground(new Color(69, 67, 164));
            FlatDarkLaf.setup();
        }else{
            menuBar.setBackground(new Color(87,134,236));
            menuBar.setForeground(Color.BLACK);
            btnDarkLightMode.setIcon(new ImageIcon("src\\main\\java\\Images\\light-mode.png"));
            btnDarkLightMode.setBackground(new Color(87,134,236));
            FlatLightLaf.setup();
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_formWindowOpened

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCapturadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturadorActionPerformed
        // TODO add your handling code here:
        new CapturadorAsignaturaFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCapturadorActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"By: Salvador Alejos Soria");
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnTemarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemarioActionPerformed
        // TODO add your handling code here:
        new VisualizadorTemas().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTemarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapturadorMateriasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapturadorMateriasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapturadorMateriasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapturadorMateriasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapturadorMateriasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnCapturador;
    private javax.swing.JToggleButton btnDarkLightMode;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnTemario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
