package com.mycompany.tap_u1p6_b;

import com.mycompany.tap_u1p6_b.pojos.Materia;
import com.mycompany.tap_u1p6_b.pojos.Subtema;
import java.awt.GridLayout;
import java.util.ArrayList;

/**
 *
 * @author Link
 */
public class CapturadorTemaFrame extends javax.swing.JFrame {

    private Materia materia;
    private int indice;
    
    private int numSubtemas = 0;
    
    private GridLayout gridLayout = new GridLayout();
    private ArrayList<Subtema> listSubtemas = new ArrayList<>();
    
    /**
     * Creates new form CapturadorTemaFrame
     */
    public CapturadorTemaFrame() {
        initComponents();
    }
    
    public CapturadorTemaFrame(Materia materia, int indice) {
        this.indice = indice;
        this.materia = materia;
        
        initComponents();
        
        setLocationRelativeTo(null);
        panelSubtemas.setLayout(gridLayout);
        
        setTitle("Subtemas para " + materia.getNombreMateria());
        labelHeader1.setText(
            "Tema " + (indice+1) + ".- " + 
                materia.getTemas().get(indice).getTituloTema()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeader1 = new org.edisoncor.gui.label.LabelHeader();
        jLabel1 = new javax.swing.JLabel();
        labelSubtemas = new javax.swing.JLabel();
        btnMas = new org.edisoncor.gui.button.ButtonAeroRound();
        btnMenos = new org.edisoncor.gui.button.ButtonAeroRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelSubtemas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelHeader1.setText("labelHeader1");

        jLabel1.setText("Número de subtemas:");

        labelSubtemas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelSubtemas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtemas.setText("0");

        btnMas.setText("+");
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        btnMenos.setText("-");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSubtemasLayout = new javax.swing.GroupLayout(panelSubtemas);
        panelSubtemas.setLayout(panelSubtemasLayout);
        panelSubtemasLayout.setHorizontalGroup(
            panelSubtemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        panelSubtemasLayout.setVerticalGroup(
            panelSubtemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelSubtemas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(labelSubtemas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSubtemas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        if(numSubtemas > 0) {
            numSubtemas--;
            labelSubtemas.setText("" + numSubtemas);
            
            generarPanels();
        }
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        numSubtemas++;
        labelSubtemas.setText("" + numSubtemas);
        
        generarPanels();
    }//GEN-LAST:event_btnMasActionPerformed

    private void generarPanels()
    {
        listSubtemas.clear();
        panelSubtemas.removeAll();
        
        gridLayout.setColumns(1);
        gridLayout.setRows(numSubtemas);
        for (int i = 0; i < numSubtemas; i++) {
            Subtema s = new Subtema();
            s.setNumSubtema(i+1);
            listSubtemas.add(s);
            
            CapturadorSubtemasPanel panel = new CapturadorSubtemasPanel(
                materia.getTemas().get(indice),
                s
            );
            panelSubtemas.add(panel);
        }
        panelSubtemas.updateUI();
        materia.getTemas().get(indice)
            .setSubtemas(listSubtemas);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapturadorTemaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapturadorTemaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapturadorTemaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapturadorTemaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapturadorTemaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAeroRound btnMas;
    private org.edisoncor.gui.button.ButtonAeroRound btnMenos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.label.LabelHeader labelHeader1;
    private javax.swing.JLabel labelSubtemas;
    private javax.swing.JPanel panelSubtemas;
    // End of variables declaration//GEN-END:variables
}
